### ISSUE TITLE
Display Manager login? Strting X as non-root user?

### ISSUE THREAD

**Issue by vlaero** [nmilosev/crouton-fedora#2]
Hello.
I've got a Fedora 23 Crouton instance running on my Chromebook - thanks.  The Freonx stuff didn't work as part of your instructions though - the directory was not there.  I needed to manually create the directory, download the freonx files and change permissions before I was able to get it to work.

I'm finding working in XFCE4 as the root user quite limiting and a lot of things just won't work.
I'm wondering if it is possible to instruct the chroot to boot into a graphical mode (ie: init 5 style) so that you can log in via the display manager?
Alternatively, is it possible to run freonx as a non-root user?
You mention that there is a Fedora bug affecting this.  Has anything changed on that front, especially with Fedora 24 now imminent?
Thanks for your work on this.

**Comment by nmilosev** [comment]
Hi there, glad you are using Crouton Fedora! Sad to hear you had issues with freonx, the Downloads folder should be mapped to the ChromeOS Downloads folder so that's where the installation should have been. I will look into it. Glad you worked it out. 

About the root issue, I am aware of it and tried to solve it in the past, sadly running as non root introduced more problems which I was too busy to fix at the time. But I managed to run it as regular user so it is definitely possible. To be honest I still haven't played with Fedora 24 to see if it works there but I definitely will. If you have time and patience please look into it, any help is well appreciated. :) There is a bug in Fedora's bugzilla which is related to what we have but it is marked as solved. 

Did you use the fast Koji build installer? How did it work? 

Thanks for reporting this. 

Cheers

**Comment by vlaero** [comment]
I used the instructions on the github page, so your version 2.0 instructions I believe.  It seemed to work OK, but not having used the previous type install I can't compare them.
I was reading about crouton and xiwi.  Do you have instructions for this also?

I'll certainly look at testing Fedora 24 and will see how it goes.  I'll try and do this before the GA release.

**Comment by nmilosev** [comment]
Please try and report back on your findings. About xiwi, it is also possible, but will require lot of work. Dummy xorg drivers are available in the Fedora repositories but you will have to compile some libraries from Crouton to make it work with the extension. I haven't tried to do it, because I just install Chromium in my chroot and use either Fedora or ChromeOS. I rarely switch between them.

Cheers!

**Comment by nmilosev** [comment]
You can now run X as non root user. :) See the updates.

The switching is broken though, I will look into it. 

Cheers!

**Comment by vlaero** [comment]
Thats good news.  I think F24 is to released today. I take it you've tried this out with a prerelease?I'll give this a look in the next couple of days.

```
  From: Nemanja Milosevic <notifications@github.com>
```

 To: nmilosev/crouton-fedora crouton-fedora@noreply.github.com 
Cc: vlaero vlaero@yahoo.com.au; Author author@noreply.github.com
 Sent: Tuesday, 21 June 2016, 23:06
 Subject: Re: [nmilosev/crouton-fedora] Display Manager login? Strting X as non-root user? (#2)

You can now run X as non root user. :) See the updates.The switching is broken though, I will look into it. Cheers!—

**Comment by nmilosev** [comment]
Fixed the switching! Was very hard :(

Anyway, try the latest version. :)

Cheers!
