### ISSUE TITLE
KDE plasma with Fedora 24

### ISSUE THREAD

**Issue by vlaero** [nmilosev/crouton-fedora#3]
Hi.
I've just installed the latest Fedora 24 version of crouton-fedora.
I've attempted to get the KDE plasma desktop environment working but the window controls are not working properly, windows borders are not there, and there are window refresh issues.
In the freon-x/install.sh file I've modified the variables as per below:
# change your DE here, for example for XFCE:

groupname="KDE Plasma Workspaces"
sessionname="plasmashell"

After a big of moving windows around to get them to refresh I can bring up konsole and issue: pkill plasmashell
This kills the desktop environment and gets me back to the chroot terminal window.

Any idea as to what could be done to fix the issue of the desktop not working properly?

**Comment by nmilosev** [comment]
Hi, I haven't tried KDE yet, will get back on this when I have some time. :)

Sounds to me it's a KDE-related issue, since I've tried both GNOME and Xfce and both worked perfectly. You may be missing some packages.

Cheers.

**Comment by vlaero** [comment]
I've changed the 'sessionname' - actually just did this in ~/.xinitrc - to '/usr/bin/startkde' and now KDE seems to be working fine.  Might be worth putting some preset commented out values in freon-x/install.sh for the various desktop environments that people that then uncomment as appropriate?

**Comment by nmilosev** [comment]
Wow that's awesome! I'm really glad you fixed it!

I like the idea of putting some comments! I will definitely do this when I get some time off. Anyway, if you try any other DE's please write your settings here so that I can include them or make a pull request. :)

Thanks for reporting this! I'm currently abroad with only my Chromebook with me and new Crouton Fedora is really running great for me. I hope that it is running great for you too and please report any issues that you find. :)

Cheers!

**Comment by nmilosev** [comment]
Closing this now. Will update scripts soon. :) Thanks!
